name: SDK Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sdk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          cache: pip
          python-version: "3.10.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Python tools
        run: |
          pip install black==22.10.0 flake8==5.0.4 isort==5.11.5

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort --check .